version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 084898106549.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...

      - docker build -t policy -f ./apps/policy/Dockerfile .
      - docker tag policy:latest 232243672857.dkr.ecr.us-east-1.amazonaws.com/policy:latest

      - docker buildx build --platform linux/amd64 -t auth -f ./apps/auth/Dockerfile .
      - docker tag auth:latest 232243672857.dkr.ecr.us-east-1.amazonaws.com/auth:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 232243672857.dkr.ecr.us-east-1.amazonaws.com/auth:latest
      - docker push 232243672857.dkr.ecr.us-east-1.amazonaws.com/policy:latest
