services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
      image: 232243672857.dkr.ecr.us-east-1.amazonaws.com/auth:latest
    command: npm run start:dev-auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  policy:
    build:
      context: .
      dockerfile: ./apps/policy/Dockerfile
      target: development
      image: 232243672857.dkr.ecr.us-east-1.amazonaws.com/policy:latest
    command: npm run start:dev-policy
    env_file:
      - ./apps/policy/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
